# Generated by Django 5.0.2 on 2025-05-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
    ]
